apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: cp-update
spec:
  components:
    linkerd:
      version: stable-2.13.7
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjDCCATOgAwIBAgIQZvMyZ8zFWOxTUb1aNf3TQzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMzA2MTQyMjAx
          MTBaFw0zMzA2MTEyMjAxMTBaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
          dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1rGzFtOYl+7Bdf9z
          U2dtYk2RA5eJXVdvLQkdFN38xdWsZHHm3KT7zKEFJGYSzsETXCG/S0HEQfLlz9iD
          tk6dKqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFIvuJBtRI9ijy2AX8YPT8YErFqOYMAoGCCqGSM49BAMCA0cAMEQCIFbt
          k3L0LxhmjU+aNuJ2aiRRY3ltz/6ATJTwrppxQ0pwAiAcAyYDrk3uxYkrjdlNTaiu
          z6Vy7O0RL/eaGTTVrG0c1Q==
          -----END CERTIFICATE-----
        identity:
          issuer:
            scheme: kubernetes.io/tls
