apiVersion: linkerd.buoyant.io/v1alpha1
kind: ControlPlane
metadata:
  name: cp-update
spec:
  components:
    linkerd:
      version: stable-2.13.6
      controlPlaneConfig:
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATSgAwIBAgIRAIJPP9PcMdn9nAz5vfDZ6U8wCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjMxMDAzMjMw
          MTI3WhcNMjgxMDAxMjMwMTI3WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDyxeuYuhw9gjKf5
          vGlfx5obe00NS4hswdvQG4PkiyNH2zsmjC/2vGOBcy352XbCi+BTmskc+08FNMbV
          xzS3DCmjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBS4adDHvirA/d3qui12CVYk5bXmXTAKBggqhkjOPQQDAgNHADBEAiBf
          9oiOEPDTkzSYfi6fPPvQLwhSXoue4WUt+t5oDz6GPwIgD6bBubfWXQKbNOMp5zOS
          sfh8Q/rYeFNZ4Na+D0j73SE=
          -----END CERTIFICATE-----
        identity:
          issuer:
            scheme: kubernetes.io/tls
